services:

  ai-service:
    build:
      context: ./ai-service

    container_name: ai-service

    ports:
      - "8000:8000"

    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-5-mini}
      JUICE_SHOP_API: ${JUICE_SHOP_API:-http://juice-shop:3000/api/Products}
      CHROMA_PATH: ${CHROMA_PATH:-/app/chroma_db}

    volumes:
      - ./ai-service:/app
      - ./ai-service/chroma_db:/app/chroma_db

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    restart: unless-stopped

  juice-shop:
    build:
      context: ./juice-shop

    container_name: juice-shop

    environment:
      AI_SERVICE_URL: http://ai-service:8000/rest/chat

    ports:
      - "3001:3000"

    restart: unless-stopped

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - ai-service

    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss

    container_name: grafana

    ports:
      - "3002:3000"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      - prometheus

    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data: