name: Publish Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build AI Service Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/ai-service:latest \
          -t ghcr.io/${{ github.repository_owner }}/ai-service:${{ github.sha }} \
          ./ai-service

      - name: Push AI Service Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ai-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/ai-service:${{ github.sha }}

      - name: Build Juice Shop Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/juice-shop:latest \
          -t ghcr.io/${{ github.repository_owner }}/juice-shop:${{ github.sha }} \
          ./juice-shop

      - name: Push Juice Shop Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/juice-shop:latest
          docker push ghcr.io/${{ github.repository_owner }}/juice-shop:${{ github.sha }}